---
title: "BIO325_kolmule_analysis"
author:

format: 
  html:
    self-contained: true
    code-tools: 
      source: true

message: FALSE
warning: FALSE
---

```{r}
#| label: setup of packages


library("here") #setting working diectory
library(tidyverse)
library(readr)
library(readxl)
```
``


```{r}
#| label: filtering out relevant columns and species
#| message: false


import_NS <- read.csv(here("data/BIO325_H2024_NS_catch_measurements.csv")) #import of all data

kolmule_import_ns <- import_NS |> 
  filter(commonname == "kolmule") #only kolmule

kolmule_otolitter_ns <-kolmule_import_ns |> 
  mutate(Oto_available = ifelse(!is.na(sex) & !is.na(maturationstage), "Yes", "No")) #this dataframe will show the number of fish with otoliths, due to us only collecting otoliths & sexing the first 30


kolmule_otolitt_agedata <- read_excel(here("data", "BIO325_kolmule_otolitt_data.xlsx"), sheet = "first_agereading") #import of the age-readings

kolmule_otolitt_agedata$fish_length <- as.numeric(kolmule_otolitt_agedata$fish_length) #setting them as numbers

```


```{r}
#| label: randomly choose 30 otoliths from the first two peaks to be age read
#| message: false

set.seed(60) #for reproducibility

first_peak_data <- kolmule_otolitter_ns |> 
  filter(Oto_available == "Yes", length >= 0.155 & length <= 0.215)

second_peak_data <- kolmule_otolitter_ns |> 
  filter(Oto_available == "Yes", length >= 0.22 & length <= 0.31)

sampled_first_peak <- first_peak_data |> 
  sample_n(30) |> 
  mutate(peak_nr = "1")

sampled_second_peak <- second_peak_data |> 
  sample_n(30) |> 
  mutate(peak_nr = "2")

sampled_fish <- bind_rows(sampled_first_peak, sampled_second_peak) 

View(sampled_fish)

#sort by station for easier navigation when getting the otoliths. 
sorted_sampled_fish <- sampled_fish |> 
  arrange(station, specimenid, length) |> 
  select (station, specimenid, length, peak_nr, serialnumber)


```



```{r}
#| label: velge ut otolitter som skal aldersleses
#| message: false

#from first peak
five_min_first_peak <- kolmule_otolitt_agedata |> 
  filter(peak_nr == 1) |> 
  arrange(otolitt_l_length_mm) |> 
  drop_na(otolitt_l_length_mm) #|> 
  #slice_head(n = 5)



five_max_first_peak <- kolmule_otolitt_agedata |> 
  filter(peak_nr == 1) |> 
  drop_na(otolitt_l_length_mm) |>
  arrange(otolitt_l_length_mm) |> 
  slice_tail(n = 5)



#from second peak
ten_min_second_peak <- kolmule_otolitt_agedata |> 
  filter(peak_nr == 2) |> #Filter for second peak
  drop_na(otolitt_l_length_mm) |>
  arrange(otolitt_l_length_mm) |> # Sort by 'length' in ascending order
  slice_head(n=10) # Select the first 10 rows


ten_max_second_peak <- kolmule_otolitt_agedata |> 
  filter(peak_nr == 2) |> 
  drop_na(otolitt_l_length_mm) |>
  arrange(otolitt_l_length_mm) |> 
  slice_tail(n=10) 

```







